### ISSUE TITLE
时空选择论的Issues若干

### ISSUE THREAD

**Issue by mrLuyao** [OpenMindClub/the_time_runner#100]
p409
1.前几段内容和p408重复
2.倒数第四行
问题：后来发现它其实更符合人脑。
改为：后来发现**这样**其实更符合人脑**规律**。

p411
中间部分的“牛逼”
问题：2.高估自己与周边朋友的牛逼程度。
改为：建议将书中的**牛逼**都替换，改为**厉害**

p413
问题：我最待见的就是文章写得啰嗦，
采铜：我最**不**待见的就是文章写得啰嗦，

p415
“未来就在硅谷纽约和波士顿。”这句话不是引用内容，应和下一段合并。
而且最好修改为：硅谷、纽约和波士顿就在未来。

p416
安替倒数第二条发言：E-Mail 或者 Email ，而非 EMail

p417
第1行，“去北京、去美国”建议改为**时间源头**

第7行，建议删掉：唯一幸运的是：**本群**的人大概都能利用这种不对等。
否则不在本群的读者会感到难受。

第9行，来—北—京 建议改为 来时间源头。 

第10行，
问题：三个字。你来北京上最差的大学都没问题。
改为：比如说，你来北京上**差一点**的大学都没问题。

p418
第7行，采铜发言建议删掉。不然他没法回母校了。。

p422
最后一行，
问题：本群国际视野应该极高了，也应该是对中国偏乐观的一群人。
改为：建议涉及“本群”怎么样的句子都删掉。

p423
第4行，
问题：二八定律**，** 
改为：二八定律**。** 

p425
我自己的发言。。。
问题：我**硬着头皮**解释一下 
改为：我**尝试**解释一下

问题：他们是围绕着科幻世界周围的。
改为：他们是围绕着《科幻世界》周围的。

p426
第4行，删掉：“群里已经开展的”几个字。建议涉及**这个群**怎样的都删

p429
安替发言，“获得”一句是安替本人的话，不用引用符号。

**Comment by ccqpein** [comment]
p417之后的内容与阳老讨论
