### ISSUE TITLE
第十三讲：运动控制Issues若干

### ISSUE THREAD

**Issue by mrLuyao** [OpenMindClub/the_time_runner#157]
p356
问题：需要处理tau来修正运动
改正：tau？

p357
问题：Fmri
改正：fMRI

p362
问题：我们做运**行**控制，做机器人，还需要生物和工程师。
改为：我们做运**动**控制，做机器人，还需要生物（学家？）和工程师。

p362
问题：代码的reliability应该比人更可靠
改为：代码的可靠性应该比人好

p364
问题：只是肌肉**行**变的信号效果会比肌电信号做得更好吗
改为：只是肌肉**形**变的信号效果会比肌电信号做得更好吗

p365
问题：A Monkey **taht** controls a robot with its thoughts
改为：A Monkey **that** controls a robot with its thoughts

问题：感受我的肌肉**行**变
改为：感受我的肌肉**形**变

p366
问题：应该是ECoG
改为：应该是ECoG（皮层脑电图）

p370
问题：就是帮助大白兔迈向星**尘**大海。
改为：就是帮组大白兔迈向星**辰**大海。

p371
问题：Fnirs 若干
改为：fNIRS

p372
问题：Attention Divisuion
改为：Attention Division

p373
问题：如果不类人类行为
改为：如果不类似人类行为

问题：现在的人工智能和机器人有一个局限是，他不能产生新知识和新行为。我们的？更改决定？和记忆不如机器⋯⋯
改为：现在的人工智能和机器人有一个局限，就是它们不能产生新知识和新行为。我们决策和记忆不如机器⋯⋯

问题：Machine Learning 不能使机器产生新知识。
改为：Machine Learning 还不能使机器产生新知识。

p378
问题：关于choking，以前写过一篇小科普
改为：关于Choking，以前写过一篇小科普

p379
问题：“这篇文章，说⋯⋯”与前面内容不用分行

p380
问题：波士顿动力公司产品大集合，这里有波士顿动力公司的一些视频
改为：“波士顿动力公司产品大集合”应该是一个超链接，超链接没有打印出来。

**Comment by ccqpein** [comment]
ok
