### ISSUE TITLE
Talk06 Issues

### ISSUE THREAD

**Issue by JeremiahZhang** [OpenMindClub/the_time_runner#158]
P157
问题：志平推荐了Gve and Take
改为：志平推荐了Give and Take

P173
问题：对外面的人gtive是为了建立名声
改为：对外面的人give是为了建立名声

P182
问题：但是这个好处也许会落在别人身上，活落在别处
改为：但是这个好处也许会落在别人身上，或落在别处

P186
问题：安替: 你们要小心
改为：安替老师引用的是 圣经马太福音6:1-2，所以建议加引用说明。

**Comment by ccqpein** [comment]
OK
