### ISSUE TITLE
Talk005 Issues

### ISSUE THREAD

**Issue by JeremiahZhang** [OpenMindClub/the_time_runner#162]
P125
问题：对学术论文的高难度改写的GRE论文时，这句整体在上下文中读起来不怎顺畅，顺然能理解
建议：是否可以修改更好的让读者读起来顺畅？

P127  P136-137 P139
问题1：在英文文章例子中出现小方格
建议：去掉小方格

问题2：:陈老师举的英文例子中，各个句子没有标明序号，这样读者去读的时候，要去数，这样不方便读者。
建议：能否像《圣经》一样，每一句表明序号？

P138
问题：不可能让一颗榕树长成一根松树
改为：不可能让一颗榕树长成一颗松树

P141
问题1：人的意向性层次通常只有4-5层，下面陈老师提到的，只有4层，漏了第四层。
建议：能否加上第4层：【我知道你知道她知道他知道X】

问题2：最后一行3个句号
改为：一个句号

**Comment by ccqpein** [comment]
p125 p138解决
