### ISSUE TITLE
『综合tiny issues』

### ISSUE THREAD

**Issue by YixuanFranco** [OpenMindClub/the_time_runner#31]
标点符号、排版之类的小问题我就放在这里了。

**Comment by woaixiaoyao5402** [comment]
P295  问题:Zoom.Quiet没加粗。

**Comment by woaixiaoyao5402** [comment]
P301 问题:Zoom.Quiet 圈子从来不是进入的是融入的用自己的圈子。
语法错误。

**Comment by woaixiaoyao5402** [comment]
P. 145
问题:

安替:大部分在中国的人。。。。。。。因为和时间源头有很大差距你光搬到中国语境就够你做的。
『后半句缺少句读，应加标点。』

**Comment by woaixiaoyao5402** [comment]
上边录入错误，我又仔细查了一下，其实是P415.安替老师的话。

**Comment by woaixiaoyao5402** [comment]
P302 王佩老师旧约引语，你的神，我的神，中间的空格可以去掉。

**Comment by baibanbao** [comment]
【为什么引用的《圣经》中“神”前面有空格？】这牵涉到中国基督教译经史上一段公案。近代外国传教士在翻译《圣经》的时候，分成两派。一派主张把God翻译成中国古籍里的“上帝”，另一派主张不承袭中国古典而翻译成“神”。两派互不相让，后来的《圣经》和合本，就有了两个译本，一个是“上帝”版，一个是“神版”，其余内容完全相同。为了节省印刷费用，现在的出版商只替换GOD的译名，由于“上帝”是两个汉字字符，“神”是一个汉字字符，于是都在“神”前面加一全角空格，形成了“ 神”这样的格式。

**Comment by woaixiaoyao5402** [comment]
多谢王佩老师提醒！
