### ISSUE TITLE
时空选择论

### ISSUE THREAD

**Issue by chaonet** [OpenMindClub/the_time_runner#95]
页数： p413
问题：我最待见的就是文章写得啰嗦
改为：我最不待见的就是文章写得啰嗦

页数： p417
问题：听上去安替和和阳志平老师意见不一致
改为：听上去安替和阳志平老师意见不一致

页数： p427
问题：几乎所有的始发性创新都发生在美国这个论据像乌云一般迅速笼罩
改为：几乎所有的始发性创新都发生在美国，这个论据像乌云一般迅速笼罩

问题：但未来固然分布不均，各处的未来又岂是一致？
改为：未来固然分布不均，但各处的未来又岂是一致？

**Comment by csufuyi** [comment]
页码填到标题里面，分成多条，方面后面的人整理，不会重复提交。
