### ISSUE TITLE
P414

### ISSUE THREAD

**Issue by Time-lady** [OpenMindClub/the_time_runner#97]
页数：p414
问题：问题是你得有基线，知道99%都想什么。...............所以写出超凡脱俗又劝大家少关心大众互联网的人，
改为：问题是你得有基线，知道99%都在想什么。...........所以写出超凡脱俗文章又劝大家少关心大众互联网的人，

备注：应该不算错误，只是不太顺。安替老师说话太简洁了。

**Comment by ccqpein** [comment]
OK
